spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpashopwithboot
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: park1124

  jpa:
    hibernate:
      ddl-auto: create
      dialect: MariaDB103Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace